@include('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <h1><strong>Privacy Policy</strong></h1>
<p>Fashday, owner of the site and any of its subdomains (collectively the &ldquo;Application&rdquo;), is committed to protecting the privacy and confidentiality of personal information entrusted to us.</p>
<p>&nbsp;</p>
<h3><strong>What Is Personal Information?</strong></h3>
<p>This Privacy Policy, together with our Terms of Use and other policies that can be found on the Application are applicable to all users of the Application, and all those who provide personal identifiable information (&ldquo;Personal Information&rdquo;) to FashDay or any its subsidiaries and affiliates (hereinafter collectively &rdquo; FashDay &ldquo;). When this Privacy Policy uses the term &ldquo;Personal Information&rdquo;, it means information which when considered in combination, identifies a particular individual, such as the individual&rsquo;s full name (first name and surname together), postal address, date of birth, and email address. When certain other non-identifiable information is directly associated with Personal Information, this other information also becomes Personal Information for purposes of this Privacy Policy.</p>
<p>&nbsp;</p>
<h3>What Is the Scope of FashDay&rsquo;s Privacy Policy?</h3>
<p>This Privacy Policy addresses our policies and procedures relating to the Personal Information of individuals, such as our customers and others accessing the Application. This Privacy Policy is applicable to the Personal Information of all users of the Application.</p>
<p>&nbsp;</p>
<h3>Personal and Other Information Collected by FashDay</h3>
<p>FashDay collects Personal Information that is voluntarily provided by you when you register, open an account, view a webcast, enter information in a webcast using the collaborative chat feature, answer our polls or surveys, register as a member, sign up for additional services, access our online forums and other services, purchase or advertise the sale of (and sell) goods or services, or communicate with us by mail, telephone or electronically. The type of information we collect and maintain could include your name, mailing address, email address, telephone number, gender, date of birth, purchase history, credit card number, complaints you may have about our products or services, a record of promotions offered to you, and your preferences. This type of information is collected, used and disclosed in accordance with the form of consent required by applicable law and its use is limited to the objectives for which it was collected as described in this Privacy Policy.</p>
<p>We may collect information through technology (such as logging IP addresses) for routine system administration purposes, to make our Application more interesting and useful to you, or to manage data and content delivery.</p>
<p>FashDay may also collect information that is stored in cookies, and we may associate this information with your Personal Information. Cookies are small pieces of information stored on your hard drive, not on the Application. We use cookies for a number of reasons. Cookies allow you to store your password without having to constantly re-enter it. Cookies also help us to tailor the Application to better match the needs and interests of our customers and members, and they allow us to better understand how users in general use our sites, which in turn helps us to focus our resources on features that are most popular with our users. You are always free to decline our cookies if your browser permits, but some parts of the Application may not work properly if you do.</p>
<p>&nbsp;</p>
<h3>Privacy of Children</h3>
<p>For those parts of the Application which may appeal directly to children under 18 years of age (&ldquo;Minor(s)&rdquo;), to complement this Privacy Policy FashDay has the following additional online privacy policies which speak specifically to the Personal Information of Minors. The following is in addition to this Privacy Policy with respect to those users. Some of the programs and services offered by FashDay may not be intended for Minors and we do not knowingly collect Personal Information from Minors on the Application. When registering on the Application however, we do not require that users confirm that they are not a Minor.</p>
<p>FashDay urges all parents and legal guardians to supervise their children&rsquo;s exploration of the Internet and any online services, and to teach their children about protecting their Personal Information online.</p>
<p>This section of the Privacy Policy outlines the information usage practices of FashDay. By accessing, browsing or using the Application, you signify your agreement to the terms and conditions of this Privacy Policy in its entirety. If you do not agree to this Privacy Policy, please do not submit your or your child&rsquo;s Personal Information to FashDay. We reserve the right, at our discretion, to change, modify, add or remove portions of our Children&rsquo;s Privacy Policy at any time.</p>
<h3>&nbsp;</h3>
<h3>Consent</h3>
<p>We reserve the right to collect, use and disclose your Personal Information without consent only as required and as permitted by law. Otherwise, Personal Information will be collected, used and disclosed in accordance with the form of consent required by applicable law and its use will be limited to the objectives for which it was collected as described herein. The form of your consent can vary from implied consent to express consent, depending upon the circumstances and the sensitivity of the type of information collected. We will rely on implied consent when we can reasonably conclude that you have given your consent by your action (e.g. by giving us your name and contact information so that we may grant access to a webcast to you) or inaction (e.g. by not exercising an ability to opt-out that is provided to you at the time your contact information is collected). This Privacy Policy identifies the purposes for which your Personal Information is collected, used and disclosed. Additional consent will be obtained from you should we wish to use or disclose your Personal Information for any additional purpose.</p>
<p>&nbsp;</p>
<h3>Why Does FashDay Collect Personal Information?</h3>
<p>FashDay may collect Personal Information for the following reasons:</p>
<p>To provide you with the products or services you have requested, including viewing a webcast;</p>
<p>To provide you with services in accordance with your account;</p>
<p>To allow us to serve you better through enhanced products, customer service and directed FashDay promotional efforts of particular interest;</p>
<p>To properly investigate and respond to any complaints, questions or concerns you may have about our products or services; and</p>
<p>To determine your eligibility for our products and services.</p>
<p>If you opt in to receive offers, promotions or other information from FashDay, your information will be used to provide you with promotional offers for FashDay products that we believe may interest you and to solicit your opinion on our products and services. If you have opted in to receive these offers, we may also use your Personal Information to ensure that your contact information is accurate and up to date.<br /> What Kind of Personal Information Does FashDay Disclose, to Whom and Why?<br /> FashDay may share your Personal Information with its respective successors and assigns, but only to the extent necessary to fulfill the purposes identified under this Privacy Policy. In addition, FashDay may disclose your Personal Information to third parties as follows:</p>
<p>To Third Parties To Perform Processing and Other Specialized Services: At times, FashDay may use outside organizations to perform specialized services such as, but not limited to, contests or collection of overdue accounts. These service providers are only given the information needed to perform those services and they are bound contractually to protect the privacy and security of your information and to limit the use of your Personal Information to the service being provided.</p>
<p>To Third Parties in the Event of Legal Reasons: We advise you that we may disclose Personal Information to the government or to other legal or regulatory authorities (i) if so ordered by a court of law or (ii) for other legal reasons, such as (a) to comply with legal process such as a search warrant, subpoena or court order; (b) to protect the company&rsquo;s rights and property; (c) to investigate reports of fraud or of users sending material using a false email address or users sending harassing, threatening, or abusive messages; (d) to protect against misuse or unauthorized use of the Application; or (e) in emergencies, such as when we believe someone&rsquo;s physical safety is at risk. In some cases, disclosure may be required by law to be without notice to you.</p>
<p>To a Third Party in the Event of a Significant Transaction or Other Event: In the case of any significant transaction or event involving FashDay, including for example (but not limited to), a sale, merger, amalgamation, financing, re-organization, bankruptcy, liquidation, or insolvency, other parties to the transaction and their professional advisors may need to have access to FashDay&rsquo;s customer lists and various databases as part of the due diligence process. In this event, FashDay would only provide such access under terms of a strict confidentiality agreement. Also, upon completion of the transaction or event, your Personal Information would be transferred to FashDay&rsquo;s successor-in-interest to be used for the purposes for which it was collected.</p>
<p>&nbsp;</p>
<h3>How Long Does FashDay Retain Personal Information?</h3>
<p>We keep your Personal Information for such period as is reasonably necessary to meet the purposes for which it was collected or to comply with any legal requirements, including statutory retention periods. When your Personal Information is no longer required for a specific purpose or legal requirement, it will be erased from our records.</p>
<h3>&nbsp;</h3>
<h3>What Security Measures Does FashDay Have in Place To Safeguard Personal Information?</h3>
<p>FashDay has implemented physical, electronic and administrative measures to protect your information from error, loss or unauthorized access. For example, we use industry-standard efforts, such as passwords and firewalls to safeguard the confidentiality of your Personal Information contained on our computer systems. In addition, our employees and any third parties we use are contractually bound to protect the confidentiality of your Personal Information and access is restricted to those with a need to know the information to carry out an identified purpose.</p>
<p>&nbsp;</p>
<h3>Non-Personal Information</h3>
<p>Non-personal or aggregated information is information that cannot be associated with or traced back to a specific person. When users browse the Application, for example, FashDay gathers information about the number of users who are viewing each page so that FashDay can learn what features are the most popular. FashDay also uses this data, both aggregated and personally identifiable, to personalize and enhance your onsite experience by displaying content and marketing messages FashDay believes will be of interest to you and to deliver content that is specific to your region. FashDay may disclose anonymous, aggregated information about the Application to third parties.</p>
<p>In addition, to help us better understand our markets, FashDay may gather demographic information for analytic purposes on an anonymous, aggregate basis. This information is not kept, used or disclosed at the individual level, but may be disclosed to third parties on an anonymous, aggregate basis.</p>
<p>&nbsp;</p>
<h3>Links to Third Party Sites</h3>
<p>Users may, through hypertext or other computer &ldquo;links&rdquo;, gain access to other applications on the Internet which are not operated by FashDay. FashDay is providing these links to you only as a convenience, and the inclusion of any link does not imply endorsement by FashDay of the application linked to. FASHDAY INC. ASSUMES NO RESPONSIBILITY FOR ANY MATERIAL OUTSIDE OF THE APPLICATIONS OPERATED BY FASHDAY INC., INCLUDING ANY APPLICATIONS WHICH MAY BE ACCESSED THROUGH A LINK ON A FASHDAY OPERATED APPLICATION. Unless otherwise indicated at a FashDay operated application, FashDay is not sponsored by or affiliated with the linked applications, and trademarks used in connection with linked applications are not trademarks of FashDay. FashDay specifically disclaims responsibility for any inadvertent viewing by a Minor of any material intended for adults on the Application or on a application accessed through use of a linked application.</p>
<h3>&nbsp;</h3>
<h3>In-world Chat and Other Communication</h3>
<p>Subject to our Terms of Use, you may be able to chat with other individuals through your access to the Application. Note that the Application is a public forum and any information that you post on the Application, even if it is Personal Information, will be publicly, and may be indefinitely, available for collection by third parties over whose use of such information we have no control. We strongly encourage you not to disclose Personal Information publicly on the Application.</p>
<p>&nbsp;</p>
<h3>How To Control How Your Personal Information is Collected, Used and Disclosed</h3>
<p>You have control over how we collect, use and disclose your Personal Information. Any comments, questions or changes regarding the collection, use and disclosure of your Personal Information will be directed to FashDay &lsquo;s Customer Service Department, as described below.</p>
<p>A request for a copy of the Personal Information we keep about you, depending on the laws of your country, must be made in writing giving details with which FashDay can identify you. Information will be provided to you in accordance with applicable law.</p>
<p>&nbsp;</p>
<h3>Questions, Updating and Accessing Your Personal Information</h3>
<p>If you have any questions or comments about FashDay &lsquo;s Privacy Policy, would like to advise us how you would like your Personal Information not to be used or disclosed, would like to &ldquo;opt-out&rdquo; at any time after granting approval or would like to access or update your Personal Information please contact us by email or mail at:</p>
<p>&nbsp;</p>
        </div>
    </div>
</div>
@endsection
